import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  productSidebar: [
    {
      type: 'doc',
      id: 'product/overview',
      label: 'Memfit AI 概览',
    },
    {
      type: 'category',
      label: '核心架构设计',
      items: [{type: 'autogenerated', dirName: 'product/architecture'}],
    },
    {
      type: 'category',
      label: '支柱组件',
      items: [{type: 'autogenerated', dirName: 'product/features'}],
    },
    {
      type: 'category',
      label: '使用场景',
      items: [{type: 'autogenerated', dirName: 'product/use-cases'}],
    },
  ],
  helpSidebar: [
    {
      type: 'category',
      label: '快速开始',
      items: [{type: 'autogenerated', dirName: 'help/quick-start'}],
    },
    {
      type: 'doc',
      id: 'help/tutorials/ai-agent',
      label: 'Agent 使用教程',
    },
    {
      type: 'doc',
      id: 'help/tutorials/knowledge-base',
      label: '知识库系统教程',
    },
    {
      type: 'doc',
      id: 'help/tutorials/skills',
      label: '如何加载和使用 SKILLS',
    },
    {
      type: 'category',
      label: '高级使用',
      link: {type: 'doc', id: 'help/tutorials/advanced'},
      items: [
        'help/tutorials/advanced/usage-and-model-performance',
        'help/tutorials/advanced/intervention-and-context',
        'help/tutorials/advanced/custom-tools-and-skills',
      ],
    },
  ],
  developerSidebar: [
    {
      type: 'category',
      label: '专注模式开发者',
      link: {type: 'doc', id: 'help/focus-mode-dev/index'},
      items: [{type: 'autogenerated', dirName: 'help/focus-mode-dev'}],
    },
  ],
};

export default sidebars;
