import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  productSidebar: [
    {
      type: 'doc',
      id: 'product/overview',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'product/architecture'}],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'product/features'}],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [{type: 'autogenerated', dirName: 'product/use-cases'}],
    },
  ],
  helpSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      items: [{type: 'autogenerated', dirName: 'help/quick-start'}],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'help/tutorials'}],
    },
  ],
};

export default sidebars;
