import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  productSidebar: [
    {
      type: 'doc',
      id: 'product/overview',
      label: 'Memfit AI 概览',
    },
    {
      type: 'category',
      label: '核心架构设计',
      items: [{type: 'autogenerated', dirName: 'product/architecture'}],
    },
    {
      type: 'category',
      label: '支柱组件',
      items: [{type: 'autogenerated', dirName: 'product/features'}],
    },
    {
      type: 'category',
      label: '使用场景',
      items: [{type: 'autogenerated', dirName: 'product/use-cases'}],
    },
  ],
  helpSidebar: [
    {
      type: 'category',
      label: '快速开始',
      items: [{type: 'autogenerated', dirName: 'help/quick-start'}],
    },
    {
      type: 'category',
      label: '教程',
      items: [{type: 'autogenerated', dirName: 'help/tutorials'}],
    },
    {
      type: 'category',
      label: '专注模式开发者',
      items: [{type: 'autogenerated', dirName: 'help/focus-mode-dev'}],
    },
  ],
};

export default sidebars;
